---
lpu-name: test-lpu
iis: false
services: []
sch-tasks: []
delete-after-days: 7
databases:
- db-path: D:\Documents\VSD\2024\db-test\queue\tcgi1.db
- db-path: D:\Documents\VSD\2024\db-test\queue\tcgi1_archive.db
  enable-vacuum: False
- db-path: D:\Documents\VSD\2024\db-test\db\msexp.db








